use std::{
    fs::{self, File},
    io::{BufWriter, Write},
    path::Path,
};

const VISUAL_GEOMETRY_ID: i64 = 1_001_001;
const VISUAL_MODEL_ID: i64 = 1_001_002;
const VISUAL_MATERIAL_ID: i64 = 1_001_003;
const COLLIDER_GEOMETRY_ID: i64 = 1_002_001;
const COLLIDER_MODEL_ID: i64 = 1_002_002;

#[derive(Debug, Clone, Copy)]
pub struct FbxVertex {
    pub position: [f64; 3],
    pub color: [f64; 4],
}

pub struct FbxMesh<'a> {
    pub name: &'a str,
    pub vertices: &'a [FbxVertex],
    /// Zero-based triangle vertex indices.
    pub triangles: &'a [[u32; 3]],
}

pub fn write_fbx(path: &Path, visual: FbxMesh<'_>, collider: FbxMesh<'_>) -> Result<(), String> {
    validate_mesh(&visual)?;
    validate_mesh(&collider)?;

    let file = File::create(path)
        .map_err(|error| format!("failed to create native FBX {}: {error}", path.display()))?;
    let mut writer = BufWriter::new(file);
    write_header(&mut writer)?;
    write_definitions(&mut writer)?;

    writeln!(writer, "Objects: {{").map_err(io_error)?;
    write_geometry(&mut writer, VISUAL_GEOMETRY_ID, visual.name, &visual, true)?;
    write_model(&mut writer, VISUAL_MODEL_ID, visual.name, false)?;
    write_material(&mut writer)?;
    write_geometry(
        &mut writer,
        COLLIDER_GEOMETRY_ID,
        collider.name,
        &collider,
        false,
    )?;
    write_model(&mut writer, COLLIDER_MODEL_ID, collider.name, true)?;
    writeln!(writer, "}}").map_err(io_error)?;

    writeln!(writer, "Connections: {{").map_err(io_error)?;
    writeln!(
        writer,
        "    C: \"OO\",{VISUAL_GEOMETRY_ID},{VISUAL_MODEL_ID}"
    )
    .map_err(io_error)?;
    writeln!(writer, "    C: \"OO\",{VISUAL_MODEL_ID},0").map_err(io_error)?;
    writeln!(
        writer,
        "    C: \"OO\",{VISUAL_MATERIAL_ID},{VISUAL_MODEL_ID}"
    )
    .map_err(io_error)?;
    writeln!(
        writer,
        "    C: \"OO\",{COLLIDER_GEOMETRY_ID},{COLLIDER_MODEL_ID}"
    )
    .map_err(io_error)?;
    writeln!(writer, "    C: \"OO\",{COLLIDER_MODEL_ID},0").map_err(io_error)?;
    writeln!(writer, "}}").map_err(io_error)?;
    writeln!(writer, "Takes: {{\n    Current: \"\"\n}}").map_err(io_error)?;
    writer
        .flush()
        .map_err(|error| format!("failed to flush native FBX: {error}"))?;
    validate_written_fbx(path, visual.vertices.len(), collider.vertices.len())
}

fn validate_mesh(mesh: &FbxMesh<'_>) -> Result<(), String> {
    if mesh.vertices.is_empty() {
        return Err(format!("FBX mesh {} has no vertices", mesh.name));
    }
    if mesh.triangles.is_empty() {
        return Err(format!("FBX mesh {} has no triangles", mesh.name));
    }
    for (face_index, face) in mesh.triangles.iter().enumerate() {
        if face
            .iter()
            .any(|index| *index as usize >= mesh.vertices.len())
        {
            return Err(format!(
                "FBX mesh {} face {} references a missing vertex",
                mesh.name, face_index
            ));
        }
    }
    Ok(())
}

fn write_header(writer: &mut impl Write) -> Result<(), String> {
    writer
        .write_all(
            br#"; FBX 7.4.0 project file
; Generated by AgriScan Studio native exporter
FBXHeaderExtension:  {
    FBXHeaderVersion: 1003
    FBXVersion: 7400
    CreationTimeStamp:  {
        Version: 1000
        Year: 1970
        Month: 1
        Day: 1
        Hour: 0
        Minute: 0
        Second: 0
        Millisecond: 0
    }
    Creator: "AgriScan Studio native FBX exporter"
}
GlobalSettings:  {
    Version: 1000
    Properties70:  {
        P: "UpAxis", "int", "Integer", "",1
        P: "UpAxisSign", "int", "Integer", "",1
        P: "FrontAxis", "int", "Integer", "",2
        P: "FrontAxisSign", "int", "Integer", "",-1
        P: "CoordAxis", "int", "Integer", "",0
        P: "CoordAxisSign", "int", "Integer", "",1
        P: "OriginalUpAxis", "int", "Integer", "",1
        P: "OriginalUpAxisSign", "int", "Integer", "",1
        P: "UnitScaleFactor", "double", "Number", "",100
        P: "OriginalUnitScaleFactor", "double", "Number", "",100
        P: "AmbientColor", "ColorRGB", "Color", "",0,0,0
        P: "DefaultCamera", "KString", "", "", "Producer Perspective"
        P: "TimeMode", "enum", "", "",0
        P: "TimeProtocol", "enum", "", "",2
        P: "SnapOnFrameMode", "enum", "", "",0
        P: "TimeSpanStart", "KTime", "Time", "",0
        P: "TimeSpanStop", "KTime", "Time", "",0
        P: "CustomFrameRate", "double", "Number", "",-1
    }
}
Documents:  {
    Count: 1
    Document: 1000000, "Scene", "Scene" {
        Properties70:  {
            P: "SourceObject", "object", "", ""
            P: "ActiveAnimStackName", "KString", "", "", ""
        }
        RootNode: 0
    }
}
References:  {
}
"#,
        )
        .map_err(io_error)
}

fn write_definitions(writer: &mut impl Write) -> Result<(), String> {
    writer
        .write_all(
            br#"Definitions:  {
    Version: 100
    Count: 5
    ObjectType: "GlobalSettings" {
        Count: 1
    }
    ObjectType: "Model" {
        Count: 2
        PropertyTemplate: "FbxNode" {
            Properties70:  {
                P: "QuaternionInterpolate", "enum", "", "",0
                P: "RotationOffset", "Vector3D", "Vector", "",0,0,0
                P: "RotationPivot", "Vector3D", "Vector", "",0,0,0
                P: "ScalingOffset", "Vector3D", "Vector", "",0,0,0
                P: "ScalingPivot", "Vector3D", "Vector", "",0,0,0
                P: "TranslationActive", "bool", "", "",0
                P: "TranslationMin", "Vector3D", "Vector", "",0,0,0
                P: "TranslationMax", "Vector3D", "Vector", "",0,0,0
                P: "RotationOrder", "enum", "", "",0
                P: "RotationSpaceForLimitOnly", "bool", "", "",0
                P: "RotationStiffnessX", "double", "Number", "",0
                P: "RotationStiffnessY", "double", "Number", "",0
                P: "RotationStiffnessZ", "double", "Number", "",0
                P: "AxisLen", "double", "Number", "",10
                P: "PreRotation", "Vector3D", "Vector", "",0,0,0
                P: "PostRotation", "Vector3D", "Vector", "",0,0,0
                P: "RotationActive", "bool", "", "",0
                P: "InheritType", "enum", "", "",1
                P: "ScalingActive", "bool", "", "",0
                P: "GeometricTranslation", "Vector3D", "Vector", "",0,0,0
                P: "GeometricRotation", "Vector3D", "Vector", "",0,0,0
                P: "GeometricScaling", "Vector3D", "Vector", "",1,1,1
                P: "MinDampRangeX", "double", "Number", "",0
                P: "MinDampRangeY", "double", "Number", "",0
                P: "MinDampRangeZ", "double", "Number", "",0
                P: "MaxDampRangeX", "double", "Number", "",0
                P: "MaxDampRangeY", "double", "Number", "",0
                P: "MaxDampRangeZ", "double", "Number", "",0
                P: "MinDampStrengthX", "double", "Number", "",0
                P: "MinDampStrengthY", "double", "Number", "",0
                P: "MinDampStrengthZ", "double", "Number", "",0
                P: "MaxDampStrengthX", "double", "Number", "",0
                P: "MaxDampStrengthY", "double", "Number", "",0
                P: "MaxDampStrengthZ", "double", "Number", "",0
                P: "PreferedAngleX", "double", "Number", "",0
                P: "PreferedAngleY", "double", "Number", "",0
                P: "PreferedAngleZ", "double", "Number", "",0
                P: "LookAtProperty", "object", "", ""
                P: "UpVectorProperty", "object", "", ""
                P: "Show", "bool", "", "",1
                P: "NegativePercentShapeSupport", "bool", "", "",1
                P: "DefaultAttributeIndex", "int", "Integer", "",-1
                P: "Freeze", "bool", "", "",0
                P: "LODBox", "bool", "", "",0
                P: "Lcl Translation", "Lcl Translation", "", "A",0,0,0
                P: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0
                P: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1
                P: "Visibility", "Visibility", "", "A",1
                P: "Visibility Inheritance", "Visibility Inheritance", "", "",1
            }
        }
    }
    ObjectType: "Geometry" {
        Count: 2
        PropertyTemplate: "FbxMesh" {
            Properties70:  {
                P: "Color", "ColorRGB", "Color", "",0.8,0.8,0.8
                P: "BBoxMin", "Vector3D", "Vector", "",0,0,0
                P: "BBoxMax", "Vector3D", "Vector", "",0,0,0
                P: "Primary Visibility", "bool", "", "",1
                P: "Casts Shadows", "bool", "", "",1
                P: "Receive Shadows", "bool", "", "",1
            }
        }
    }
    ObjectType: "Material" {
        Count: 1
        PropertyTemplate: "FbxSurfaceLambert" {
            Properties70:  {
                P: "ShadingModel", "KString", "", "", "Lambert"
                P: "MultiLayer", "bool", "", "",0
                P: "EmissiveColor", "Color", "", "A",0,0,0
                P: "EmissiveFactor", "Number", "", "A",1
                P: "AmbientColor", "Color", "", "A",0.2,0.2,0.2
                P: "AmbientFactor", "Number", "", "A",1
                P: "DiffuseColor", "Color", "", "A",0.8,0.8,0.8
                P: "DiffuseFactor", "Number", "", "A",1
                P: "TransparentColor", "Color", "", "A",0,0,0
                P: "TransparencyFactor", "Number", "", "A",0
            }
        }
    }
}
"#,
        )
        .map_err(io_error)
}

fn write_geometry(
    writer: &mut impl Write,
    id: i64,
    name: &str,
    mesh: &FbxMesh<'_>,
    include_colors: bool,
) -> Result<(), String> {
    writeln!(
        writer,
        "    Geometry: {id}, \"Geometry::{name}_mesh\", \"Mesh\" {{"
    )
    .map_err(io_error)?;
    writeln!(writer, "        GeometryVersion: 124").map_err(io_error)?;

    let vertex_value_count = mesh.vertices.len() * 3;
    writeln!(writer, "        Vertices: *{vertex_value_count} {{").map_err(io_error)?;
    write_f64_array(
        writer,
        mesh.vertices
            .iter()
            .flat_map(|vertex| vertex.position.into_iter()),
    )?;
    writeln!(writer, "        }}").map_err(io_error)?;

    let index_value_count = mesh.triangles.len() * 3;
    writeln!(
        writer,
        "        PolygonVertexIndex: *{index_value_count} {{"
    )
    .map_err(io_error)?;
    write_i64_array(
        writer,
        mesh.triangles
            .iter()
            .flat_map(|face| [face[0] as i64, face[1] as i64, -(face[2] as i64) - 1]),
    )?;
    writeln!(writer, "        }}").map_err(io_error)?;

    if include_colors {
        writeln!(writer, "        LayerElementColor: 0 {{").map_err(io_error)?;
        writeln!(writer, "            Version: 101").map_err(io_error)?;
        writeln!(writer, "            Name: \"scan_vertex_color\"").map_err(io_error)?;
        writeln!(writer, "            MappingInformationType: \"ByVertice\"").map_err(io_error)?;
        writeln!(writer, "            ReferenceInformationType: \"Direct\"").map_err(io_error)?;
        let color_value_count = mesh.vertices.len() * 4;
        writeln!(writer, "            Colors: *{color_value_count} {{").map_err(io_error)?;
        write_f64_array(
            writer,
            mesh.vertices
                .iter()
                .flat_map(|vertex| vertex.color.into_iter()),
        )?;
        writeln!(writer, "            }}").map_err(io_error)?;
        writeln!(writer, "        }}").map_err(io_error)?;
    }

    writeln!(writer, "        LayerElementMaterial: 0 {{").map_err(io_error)?;
    writeln!(writer, "            Version: 101").map_err(io_error)?;
    writeln!(writer, "            MappingInformationType: \"AllSame\"").map_err(io_error)?;
    writeln!(
        writer,
        "            ReferenceInformationType: \"IndexToDirect\""
    )
    .map_err(io_error)?;
    writeln!(
        writer,
        "            Materials: *1 {{\n                a: 0\n            }}"
    )
    .map_err(io_error)?;
    writeln!(writer, "        }}").map_err(io_error)?;
    writeln!(writer, "        Layer: 0 {{").map_err(io_error)?;
    writeln!(writer, "            Version: 100").map_err(io_error)?;
    if include_colors {
        writeln!(
            writer,
            "            LayerElement:  {{\n                Type: \"LayerElementColor\"\n                TypedIndex: 0\n            }}"
        )
        .map_err(io_error)?;
    }
    writeln!(
        writer,
        "            LayerElement:  {{\n                Type: \"LayerElementMaterial\"\n                TypedIndex: 0\n            }}"
    )
    .map_err(io_error)?;
    writeln!(writer, "        }}").map_err(io_error)?;
    writeln!(writer, "    }}").map_err(io_error)
}

fn write_model(writer: &mut impl Write, id: i64, name: &str, collider: bool) -> Result<(), String> {
    writeln!(writer, "    Model: {id}, \"Model::{name}\", \"Mesh\" {{").map_err(io_error)?;
    writeln!(writer, "        Version: 232").map_err(io_error)?;
    writeln!(writer, "        Properties70:  {{").map_err(io_error)?;
    writeln!(
        writer,
        "            P: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\",0,0,0"
    )
    .map_err(io_error)?;
    writeln!(
        writer,
        "            P: \"Lcl Rotation\", \"Lcl Rotation\", \"\", \"A\",0,0,0"
    )
    .map_err(io_error)?;
    writeln!(
        writer,
        "            P: \"Lcl Scaling\", \"Lcl Scaling\", \"\", \"A\",1,1,1"
    )
    .map_err(io_error)?;
    if collider {
        writeln!(
            writer,
            "            P: \"Collision\", \"KString\", \"\", \"U\", \"triangle_mesh\""
        )
        .map_err(io_error)?;
    }
    writeln!(writer, "        }}").map_err(io_error)?;
    writeln!(writer, "        Shading: T").map_err(io_error)?;
    writeln!(writer, "        Culling: \"CullingOff\"").map_err(io_error)?;
    writeln!(writer, "    }}").map_err(io_error)
}

fn write_material(writer: &mut impl Write) -> Result<(), String> {
    writeln!(
        writer,
        "    Material: {VISUAL_MATERIAL_ID}, \"Material::scan_vertex_color\", \"\" {{"
    )
    .map_err(io_error)?;
    writeln!(writer, "        Version: 102").map_err(io_error)?;
    writeln!(writer, "        ShadingModel: \"lambert\"").map_err(io_error)?;
    writeln!(writer, "        MultiLayer: 0").map_err(io_error)?;
    writeln!(
        writer,
        "        Properties70:  {{\n            P: \"DiffuseColor\", \"Color\", \"\", \"A\",1,1,1\n            P: \"DiffuseFactor\", \"Number\", \"\", \"A\",1\n        }}"
    )
    .map_err(io_error)?;
    writeln!(writer, "    }}").map_err(io_error)
}

fn write_f64_array(
    writer: &mut impl Write,
    values: impl IntoIterator<Item = f64>,
) -> Result<(), String> {
    write!(writer, "            a: ").map_err(io_error)?;
    for (index, value) in values.into_iter().enumerate() {
        if index > 0 {
            write!(writer, ",").map_err(io_error)?;
        }
        if index > 0 && index % 24 == 0 {
            write!(writer, "\n               ").map_err(io_error)?;
        }
        write!(writer, "{value:.9}").map_err(io_error)?;
    }
    writeln!(writer).map_err(io_error)
}

fn write_i64_array(
    writer: &mut impl Write,
    values: impl IntoIterator<Item = i64>,
) -> Result<(), String> {
    write!(writer, "            a: ").map_err(io_error)?;
    for (index, value) in values.into_iter().enumerate() {
        if index > 0 {
            write!(writer, ",").map_err(io_error)?;
        }
        if index > 0 && index % 36 == 0 {
            write!(writer, "\n               ").map_err(io_error)?;
        }
        write!(writer, "{value}").map_err(io_error)?;
    }
    writeln!(writer).map_err(io_error)
}

fn validate_written_fbx(
    path: &Path,
    visual_vertex_count: usize,
    collider_vertex_count: usize,
) -> Result<(), String> {
    let metadata = fs::metadata(path)
        .map_err(|error| format!("failed to stat native FBX {}: {error}", path.display()))?;
    if metadata.len() < 512 {
        return Err("native FBX output is unexpectedly small".to_string());
    }
    let data = fs::read_to_string(path)
        .map_err(|error| format!("failed to validate native FBX: {error}"))?;
    for required in [
        "; FBX 7.4.0 project file",
        "FBXVersion: 7400",
        "Model::scan_surface",
        "Model::UCX_scan_surface_00",
        "Connections:",
    ] {
        if !data.contains(required) {
            return Err(format!("native FBX validation failed: missing {required}"));
        }
    }
    let visual_values = visual_vertex_count * 3;
    let collider_values = collider_vertex_count * 3;
    if data.matches(&format!("Vertices: *{visual_values}")).count() == 0
        || data
            .matches(&format!("Vertices: *{collider_values}"))
            .count()
            == 0
    {
        return Err("native FBX validation failed: vertex array count mismatch".to_string());
    }
    Ok(())
}

fn io_error(error: std::io::Error) -> String {
    format!("native FBX write failed: {error}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        process::Command,
        time::{SystemTime, UNIX_EPOCH},
    };

    #[test]
    fn native_fbx_round_trips_through_assimp_when_available() {
        let vertices = [
            FbxVertex {
                position: [-0.5, 0.0, 0.0],
                color: [1.0, 0.0, 0.0, 1.0],
            },
            FbxVertex {
                position: [0.5, 0.0, 0.0],
                color: [0.0, 1.0, 0.0, 1.0],
            },
            FbxVertex {
                position: [0.0, 1.0, 0.0],
                color: [0.0, 0.0, 1.0, 1.0],
            },
        ];
        let triangles = [[0, 1, 2]];
        let stamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock before unix epoch")
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "agriscan-native-fbx-{}-{stamp}.fbx",
            std::process::id()
        ));

        write_fbx(
            &path,
            FbxMesh {
                name: "scan_surface",
                vertices: &vertices,
                triangles: &triangles,
            },
            FbxMesh {
                name: "UCX_scan_surface_00",
                vertices: &vertices,
                triangles: &triangles,
            },
        )
        .expect("native FBX export");

        let contents = fs::read_to_string(&path).expect("read native FBX");
        assert!(contents.contains("LayerElementColor"));
        assert!(contents.contains("PolygonVertexIndex: *3"));

        if let Ok(output) = Command::new("assimp").arg("info").arg(&path).output() {
            assert!(
                output.status.success(),
                "Assimp rejected native FBX:\n{}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
            let report = String::from_utf8_lossy(&output.stdout);
            assert!(
                report
                    .lines()
                    .any(|line| line.starts_with("Meshes:") && line.ends_with('2')),
                "{report}"
            );
        }

        let _ = fs::remove_file(path);
    }
}
